version: '3.8'

services:
  vault1:
    image: hashicorp/vault:1.17.3
    container_name: vault1
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: vault1
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -dev -dev-root-token-id="vault1"

  vault2:
    image: hashicorp/vault:1.17.3
    container_name: vault2
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: vault2
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8201
    ports:
      - "8201:8201"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -dev -dev-root-token-id="vault2"

networks:
  default:
    name: vault-net
    driver: bridge
